templates:
  name: default
mapping:
  index: "/web"
  home: "/web/home"
  page: "/web/page"
  bookrack: "/web/bookrack"
  user: "/web/user"
website:
  name: "飞鸟小说"
  keywords: "飞鸟小说"
  description: "飞鸟小说"