spring:
  profiles:
    include: service-prod

spider:
  # 0:cpu*2 线程数启动
  threadNum: 3
  retryTimes: 5
  sleepTime: 3000
  timeOut: 60000
  queueNum: 500
baiduPush:
  pushUrl: "http://data.zz.baidu.com/urls?site=xxx&token=xxx"
  siteBaseUrl: "https://www.xxx.com/web/page/"