spring:
  data:
    mongodb:
      uri: mongodb://admin:admin.2022@127.0.0.1:27017/?authSource=admin
      database: birds
      auto-index-creation: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: admin.2022
    jedis:
      pool:
        max-active: 1000
        max-wait: 100
        max-idle: 100
        min-idle: 4
#    lettuce:
#      shutdown-timeout: 100 # 关闭超时时间
#      pool:
#        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
#        max-idle: 8 # 连接池中的最大空闲连接
#        max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        min-idle: 0 # 连接池中的最小空闲连接
logging:
  config: classpath:logback-spring.xml
location:
  image: image/
novelImagePath: /data/
contentError:
  textLoad: "章节内容获取中，请稍后重试"
  textError: "章节内容错误"
  nameError: "章节错误"
jwt:
  tokenSecretKey: "birdsnovel"